spring.application.name=DriverVehicleService
server.port=8081

# MongoDB Atlas connection (isolated database per microservice)
spring.data.mongodb.uri=mongodb+srv://it24510014_db_user:kkrb6L0alvD8meN3@ridelink.5x6hidw.mongodb.net/?appName=RideLink
spring.data.mongodb.database=ridelink_driver_db

# JWT Configuration (shared secret with Account Service)
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration-ms=3600000
