spring.application.name=RideLink

# Account Service configuration
server.port=8080

# MongoDB Atlas connection — pulled from the MONGODB_URI environment variable.
spring.data.mongodb.uri=mongodb+srv://it24510014_db_user:kkrb6L0alvD8meN3@ridelink.5x6hidw.mongodb.net/?appName=RideLink

# JWT
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration-ms=360000